name: Backend Deploy
on:
  pull_request:
  push:
    branches:
      - master
    paths:
    - 'backend/**'
jobs:
  build:
    runs-on: ubuntu-18.04
    steps:
    - uses: actions/checkout@v1
    - name: Set up Python 3.6.8
      uses: actions/setup-python@v1
      with:
        python-version: 3.6.8
    - name: Install dependencies
      working-directory: ./backend
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
